# Generated by Django 4.0.3 on 2023-11-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_register_name', models.CharField(max_length=255)),
                ('user_register_email', models.EmailField(max_length=255)),
                ('user_register_number', models.CharField(max_length=255)),
                ('user_register_user', models.CharField(max_length=255)),
                ('user_register_pic', models.ImageField(null=True, upload_to='images/')),
                ('user_password', models.CharField(max_length=255)),
            ],
        ),
    ]
