# Generated by Django 4.0.3 on 2023-11-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=255)),
                ('cat_image', models.ImageField(null=True, upload_to='uploads')),
                ('cat_product_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_price', models.FloatField()),
                ('product_image', models.CharField(max_length=255)),
                ('product_disc', models.CharField(max_length=400, null=True)),
                ('product_cat', models.IntegerField(null=True)),
            ],
        ),
    ]
