# Generated by Django 4.0.3 on 2023-11-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopapp', '0002_category_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_color',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
