# Generated by Django 4.0.3 on 2023-11-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopapp', '0006_alter_category_cat_image_alter_product_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_user', models.CharField(max_length=255)),
                ('cart_id', models.IntegerField()),
                ('cart_name', models.CharField(max_length=255)),
                ('cart_quantity', models.IntegerField()),
                ('cart_price', models.FloatField()),
                ('cart_disc', models.CharField(max_length=400, null=True)),
                ('cart_image', models.ImageField(null=True, upload_to='carts')),
                ('total_price', models.FloatField(default=0)),
            ],
        ),
    ]
