# Generated by Django 4.2.7 on 2023-11-29 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eshopapp", "0007_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="cart_color",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cart",
            name="cart_image",
            field=models.FileField(null=True, upload_to="carts"),
        ),
        migrations.AlterField(
            model_name="category",
            name="cat_image",
            field=models.FileField(null=True, upload_to="cats"),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_image",
            field=models.FileField(null=True, upload_to="products"),
        ),
        migrations.AlterField(
            model_name="userregistration",
            name="user_register_pic",
            field=models.FileField(null=True, upload_to="images/"),
        ),
    ]
