# Generated by Django 4.2.7 on 2023-11-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eshopapp", "0008_cart_cart_color_alter_cart_cart_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("list_user", models.CharField(max_length=255, null=True)),
                ("list_name", models.CharField(max_length=255)),
                ("list_image", models.FileField(null=True, upload_to="lists")),
                ("list_price", models.FloatField()),
            ],
        ),
    ]
