# Generated by Django 4.2.7 on 2023-11-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eshopapp", "0009_wishlist"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("o_product_name", models.CharField(max_length=255)),
                ("o_product_qty", models.IntegerField()),
                ("o_product_price", models.FloatField()),
                ("o_product_image", models.FileField(null=True, upload_to="orders")),
                ("o_product_total", models.FloatField(default=0)),
                ("current_user", models.CharField(max_length=255)),
                ("delvry_fname", models.CharField(max_length=255)),
                ("delvry_lname", models.CharField(max_length=255)),
                ("delvry_mail", models.CharField(max_length=255)),
                ("delvry_phone", models.CharField(max_length=255)),
                ("delvry_address", models.TextField()),
                ("delvry_upi", models.CharField(max_length=255)),
                ("delvry_type", models.CharField(default="cod", max_length=255)),
            ],
        ),
    ]
