# Generated by Django 4.2.7 on 2023-12-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eshopapp", "0011_wishlist_list_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="cat_count",
            field=models.IntegerField(null=True),
        ),
    ]
