# Generated by Django 4.2.7 on 2023-12-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eshopapp", "0012_category_cat_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="cat_count",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
