# Generated by Django 4.2.7 on 2023-12-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eshopapp", "0013_product_product_id_alter_category_cat_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="Purchased",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("p_product_name", models.CharField(max_length=255)),
                ("p_product_qty", models.IntegerField()),
                ("p_product_price", models.FloatField()),
                ("p_product_image", models.FileField(null=True, upload_to="orders")),
                ("p_product_total", models.FloatField(default=0)),
                ("current_user", models.CharField(max_length=255)),
                ("delvry_address", models.TextField()),
                ("delvry_upi", models.CharField(default="inda@upi", max_length=255)),
                ("delvry_type", models.CharField(default="cod", max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="order",
            name="delvry_upi",
            field=models.CharField(default="inda@upi", max_length=255),
        ),
    ]
